### ISSUE TITLE
現在在Safari及Chrome似乎沒辦法用？

### ISSUE THREAD

**Issue by maclaren0804** [happydenn/mixerbox-plus#1]
我在 Mac 10.12.5 的系統上使用Safari Version 11.0 (12604.1.38.1.7)及Chrome Version 60.0.3112.113 (Official Build) (64-bit)，都安裝了 Tampermonkey，再安裝您的script，也看到Enabled，不過還是沒有放大的功能，是否現在已不能使用呢？

**Comment by happydenn** [comment]
詳細修正: #2 
因為MixerBox更換了他們播放YouTube player的iframe位置，已經更新囉！請下載新版即可～

**Comment by maclaren0804** [comment]
感謝你！！

2017-11-16 1:47 GMT+08:00 Denny Tsai <notifications@github.com>:
